# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AbsoluteDarhk' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod “TextFieldEffects”

  # Pods for AbsoluteDarhk

  target 'AbsoluteDarhkTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AbsoluteDarhkUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
